### PR TITLE
Updated Readme with reference to BjyAuthorize

### PR DESCRIPTION
**Pull request by Hounddog**

### CODE REVIEW

**Comment by Thinkscape** [comment]
What is a "bk" ?

**Comment by Hounddog** [comment]
I just renamed it so we do not loose out on the original README bk is just backup for me :)

**Comment by Thinkscape** [comment]
Nah. delete it. That's what VCS is for.

**Comment by matuszeman** [comment]
I think we can simply delete whole repo including source-code as nobody is planning to maintain it anymore. README with links to different solutions should be enough for now.

**Comment by Hounddog** [comment]
Well, i understood that BjyAuthorize will be converted to ZfcAcl in the future. we can discuss this but for now at least a hint that it is not maintained anymore must be given

**Pull request merged**
